### ISSUE TITLE
ForkingExecutor does not seem to broadcast subprocess exit code

### ISSUE THREAD

**Issue by labianchin** [spotify/flo#102]
It seems that [`FloForkingExecutor`](https://github.com/spotify/flo/blob/master/flo-runner/src/main/java/com/spotify/flo/context/ForkingExecutor.java) does not handle the subprocess exit code, hence the main process would not exit with code 50.

As an example, consider the following "pseudo" Flo Task:

```scala
com.spotify.flo.defTask("foo")
   .process(() => sys.exit(50))
```

## Why is that important

Because Flo is useful with Styx and Styx support a [exit code 50](https://github.com/spotify/styx/blob/master/doc/design-overview.md#workflow-state-graph) as a signal to not retry.

> Exit code 50 will cause an immediate failure of the workflow instance (no re-try will be scheduled). This can be used by workflow to indicate an unrecoverable failure and instruct Styx not to retry.

This is used internally in Spotify when a data validation fails in a non recoverable way.

**Comment by danielnorberg** [comment]
Proposed fix: https://github.com/spotify/flo/pull/106

With the above PR you can do the following to make FloRunner exit with status code 50:

```
com.spotify.flo.defTask("foo")
   .process(() => throw new NotRetriable())
```

This is similar to how the `NotReady` exception can be used to signal that e.g. dependencies are missing and make `FloRunner` exit with status code 20.

**Comment by labianchin** [comment]
Great. #106 mitigates the issue, but it does not fix.

We have internal validation libraries that do exit status code 50 (regardless of flo or luigi). Should they move into depending on flo so that they can throw this `NotRetriable` exception?

**Comment by danielnorberg** [comment]
Would it be possible for those libraries to depend on flo and throw NotRetriable? Can you explain how those libraries are also used in luigi workflows (assuming they are java/scala and not python)?

**Comment by rouzwawi** [comment]
One option is to only return the result of validation to the caller and allow the decision to be made in the workflow code instead. That would remove the need for a flo dependency in the validation libraries.

**Comment by danielnorberg** [comment]
@labianchin  Can we close this?
