### ISSUE TITLE
flo-scio: support for scio 0.5.6 and Beam SDK 2.5.0

### ISSUE THREAD

**Issue by labianchin** [spotify/flo#133]
https://github.com/spotify/scio/releases/tag/v0.5.6

**Comment by danielnorberg** [comment]
Afaict nothing prevents users from using `v0.5.6`

**Comment by labianchin** [comment]
AFAIK there are incompatible things:

`scio-core:0.5.6` depends on `beam-sdk:2.5.0` which depends on `google-api-client:1.23.0`


`flo-bigquery` depedens on `google-cloud-bigquery:0.21.0-beta` which depends on `google-api-services-bigquery:v2-rev347-1.22.0` which depends on `google-api-client:1.23.0`.

So, time to upgrade `google-cloud-biqquery`?

**Comment by NatashaL** [comment]
> @labianchin:
> this: https://github.com/spotify/flo/blob/master/contrib/flo-bigquery/src/main/java/com/spotify/flo/contrib/bigquery/DefaultBigQueryClient.java#L25 is only compatible with `1.22.0`. `import com.google.cloud.WaitForOption;` does not exist on `1.23.0`

**Comment by danielnorberg** [comment]
The `com.google.cloud.WaitForOption` class is in `google-cloud-core`, not in `google-api-client`.

**Comment by danielnorberg** [comment]
@labianchin I was able to use scio `0.5.6` simply by specifying that version in my `build.sbt`, no flo changes needed. Both the flo and scio BigQuery integrations worked as well.
