### ISSUE TITLE
Serialization doesn't work with forking

### ISSUE THREAD

**Issue by kanterov** [spotify/flo#170]
flo version: 0.4.1

Minimal reproducible example:

```java
package com.spotify.data.clickhouse;

import com.spotify.flo.Task;
import com.spotify.flo.context.FloRunner;
import org.apache.beam.sdk.options.PipelineOptions;
import org.apache.beam.sdk.options.PipelineOptionsFactory;

public class App {
  public static void main(String[] args) {
    PipelineOptions opts = PipelineOptionsFactory.fromArgs(args).create();

    FloRunner
        .runTask(task(opts))
        .waitAndExit();
  }

  public static Task<String> task(PipelineOptions opts) {
    return Task.named("task")
        .ofType(String.class)
        .process(opts::toString);
  }
}
```

## Workaround

Create `resources/flo.conf` and put `flo.forking = false` there.

**Comment by danielnorberg** [comment]
Flo uses kryo for serialization and `org.apache.beam.sdk.options.PipelineOptions` is not kryo-serializable.

This can be worked around by instantiating the `PipelineOptions` inside the task, or passing in a closure instead:

```java
import com.spotify.flo.Task;
import com.spotify.flo.TaskBuilder.F0;
import org.apache.beam.sdk.options.PipelineOptions;
import org.apache.beam.sdk.options.PipelineOptionsFactory;

public class App {

  public static void main(String[] args) {
    F0<PipelineOptions> opts = () -> PipelineOptionsFactory.fromArgs(args).create();

    FloRunner
        .runTask(task(opts))
        .waitAndExit();
  }

  public static Task<String> task(F0<PipelineOptions> opts) {
    return Task.named("task")
        .ofType(String.class)
        .process(() -> opts.get().toString());
  }
}
```

**Comment by danielnorberg** [comment]
The difficulty of serializing `PipelineOptions` seems somewhat intentional: 

> {@link PipelineOptions} is intentionally <i>not</i> marked {@link java.io.Serializable}

https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/options/PipelineOptions.java#L182

However, it is json serializable. Would perhaps be good if flo could attempt json serialization for such types.

**Comment by danielnorberg** [comment]
They really don't want `PipelineOptions` to be java serialized: 

> PipelineOptions objects are not serializable

https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/options/ProxyInvocationHandler.java#L175

**Comment by kanterov** [comment]
Not entirely fixed, but error messages are improved in https://github.com/spotify/flo/pull/178

**Comment by danielnorberg** [comment]
Should get much better error messages in https://github.com/spotify/flo/pull/179
